### ISSUE TITLE
Besides JSON formatted value, send simple values to MQTT also

### ISSUE THREAD

**Issue by alex-sever-h** [TinkerWorks/HomeSensorHub#18]
While JSON formatted data has the advantage of accurate timestamps and measurement units, integrating in haas would be a lot simpler if a topic with just the value was presented.

eg. right now we have messages like 
somesensor/temperature/current   { "value": 25 , "unit":"celsius", "timestamp":"3:14 3.14.3141"}
it would be nice to also have:
somesensor/temperature/current/value 25
somesensor/temperature/current/unit celsius
somesensor/temperature/current/timestamp "3:14 3.14.3141"

This would not have the advantage of simply link the value and timestamp, but would allow for easier debugging and tinkering.

Also, should be easy to implement in the current architecture

**Comment by BabyCakes13** [comment]
I suppose we should not discard the somesensor/temperature/current  { "value": 25 , "unit":"celsius", "timestamp":"3:14 3.14.3141"}, rather just also add the current/value, current/unit and so on topics for easier haas linkage. The /current topic which contains the payload with the whole information should also be kept for database collection.

**Comment by BabyCakes13** [comment]
In #20 you can see the information we are currently sending. I'm not sure whether we should send all this data to MQTT or not. 

The JSON payload will be used (for now) for storing the collected information to a database; I am not sure how we're going to get the information for the database: if  for the DB routing we collect the packages from MQTT and send them to the DB, then it makes sense to also send the JSON payload to MQTT. On the other hand, if we send the internal Payload to a DB sink without also going through MQTT, I see no reason for sending the JSON payload as well as the simple values to MQTT, since we already have all the information in the simple publishes. 

What do you think @alex-sever-h?
